[package]
name = "work"
version = "0.1.0"
authors = ["g-w1 <jacoblevgw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.23.1"
clap = "3.0.0-beta.1"
skim = "0.8.1"
